/**
 * クッキー型に使える Font Awesome のアイコン。
 *
 * ⚠ solid（塗りつぶし）だけを使う。線だけのアイコンは輪郭が二重になり、
 *   刃が細くなりすぎて型にならない。
 *
 * ⚠ 全部（2000個以上）を読み込むと束が重くなるので、型に向く形だけを選んで並べている。
 *   名前を1行足せば増やせる。
 *
 * アイコンの著作権は Font Awesome（CC BY 4.0）。表示にあたっては出典を明記すること。
 * https://fontawesome.com/license/free
 */
import {
  faCat,
  faDog,
  faHorse,
  faFish,
  faDove,
  faCrow,
  faFrog,
  faHippo,
  faOtter,
  faSpider,
  faDragon,
  faKiwiBird,
  faShrimp,
  faPaw,
  faWorm,
  faMosquito,
  faLocust,
  faBugs,
  faAppleWhole,
  faCarrot,
  faLemon,
  faPepperHot,
  faIceCream,
  faCookie,
  faCakeCandles,
  faPizzaSlice,
  faDrumstickBite,
  faBreadSlice,
  faEgg,
  faCheese,
  faHotdog,
  faBurger,
  faCandyCane,
  faMugHot,
  faBacon,
  faFishFins,
  faPlateWheat,
  faStroopwafel,
  faGhost,
  faGift,
  faTree,
  faSnowflake,
  faHollyBerry,
  faCrown,
  faBell,
  faSleigh,
  faMenorah,
  faStarAndCrescent,
  faHatWizard,
  faSkull,
  faMask,
  faWandMagicSparkles,
  faSun,
  faCloud,
  faMoon,
  faLeaf,
  faSeedling,
  faFire,
  faBolt,
  faDroplet,
  faFeather,
  faClover,
  faMountain,
  faRainbow,
  faUmbrella,
  faWind,
  faCar,
  faPlane,
  faRocket,
  faShip,
  faTrain,
  faTruck,
  faBicycle,
  faMotorcycle,
  faTractor,
  faHelicopter,
  faSailboat,
  faBus,
  faHeart,
  faStar,
  faMusic,
  faTrophy,
  faMedal,
  faBookmark,
  faAnchor,
  faKey,
  faLightbulb,
  faPuzzlePiece,
  faGem,
  faChessKnight,
  faFootball,
  faBaseball,
  faBasketball,
  faFutbol,
  faShapes,
  faCertificate,
  faFan,
  faHandPeace,
  faHandSpock,
  faThumbsUp,
  faFaceSmile,
  faFaceGrinHearts,
  faUser,
  faChild,
  faPersonSkating,
  faHouse,
  faGuitar,
  faPalette,
  faCamera,
  faEnvelope,
  faGraduationCap,
  faShieldHalved,
  faRobot,
  faDice,
  faGamepad,
  faBellConcierge,
  faCouch,
  faShirt,
  faTooth,
  faGlasses,
  faHeadphones,
  faBook,
} from '@fortawesome/free-solid-svg-icons'

export interface CutterIcon {
  /** Font Awesome での名前 */
  name: string
  /** 検索に使う日本語の読み */
  keywords: string
  category: string
  /** SVG の d 属性 */
  path: string
}

export const ICON_CATEGORIES = [
  '動物',
  '食べもの',
  '行事',
  'しぜん',
  'のりもの',
  'かたち',
  'ひと',
  'くらし',
] as const

export const CUTTER_ICONS: CutterIcon[] = [
  { name: 'cat', keywords: 'ねこ 猫 キャット', category: '動物', path: faCat.icon[4] as string },
  { name: 'dog', keywords: 'いぬ 犬 ドッグ', category: '動物', path: faDog.icon[4] as string },
  { name: 'horse', keywords: 'うま 馬 ホース', category: '動物', path: faHorse.icon[4] as string },
  { name: 'fish', keywords: 'さかな 魚 フィッシュ', category: '動物', path: faFish.icon[4] as string },
  { name: 'dove', keywords: 'はと 鳩 とり 鳥', category: '動物', path: faDove.icon[4] as string },
  { name: 'crow', keywords: 'からす カラス とり 鳥', category: '動物', path: faCrow.icon[4] as string },
  { name: 'frog', keywords: 'かえる カエル', category: '動物', path: faFrog.icon[4] as string },
  { name: 'hippo', keywords: 'かば カバ', category: '動物', path: faHippo.icon[4] as string },
  { name: 'otter', keywords: 'かわうそ カワウソ', category: '動物', path: faOtter.icon[4] as string },
  { name: 'spider', keywords: 'くも クモ 蜘蛛', category: '動物', path: faSpider.icon[4] as string },
  { name: 'dragon', keywords: 'ドラゴン りゅう 竜', category: '動物', path: faDragon.icon[4] as string },
  { name: 'kiwi-bird', keywords: 'キーウィ とり 鳥', category: '動物', path: faKiwiBird.icon[4] as string },
  { name: 'shrimp', keywords: 'えび エビ 海老', category: '動物', path: faShrimp.icon[4] as string },
  { name: 'paw', keywords: 'にくきゅう 肉球 あしあと 足跡', category: '動物', path: faPaw.icon[4] as string },
  { name: 'worm', keywords: 'いもむし 芋虫', category: '動物', path: faWorm.icon[4] as string },
  { name: 'mosquito', keywords: 'か 蚊 むし 虫', category: '動物', path: faMosquito.icon[4] as string },
  { name: 'locust', keywords: 'ばった バッタ むし 虫', category: '動物', path: faLocust.icon[4] as string },
  { name: 'bugs', keywords: 'むし 虫 アリ', category: '動物', path: faBugs.icon[4] as string },
  { name: 'apple-whole', keywords: 'りんご リンゴ', category: '食べもの', path: faAppleWhole.icon[4] as string },
  { name: 'carrot', keywords: 'にんじん ニンジン 人参', category: '食べもの', path: faCarrot.icon[4] as string },
  { name: 'lemon', keywords: 'レモン', category: '食べもの', path: faLemon.icon[4] as string },
  { name: 'pepper-hot', keywords: 'とうがらし 唐辛子', category: '食べもの', path: faPepperHot.icon[4] as string },
  { name: 'ice-cream', keywords: 'アイス アイスクリーム', category: '食べもの', path: faIceCream.icon[4] as string },
  { name: 'cookie', keywords: 'クッキー', category: '食べもの', path: faCookie.icon[4] as string },
  { name: 'cake-candles', keywords: 'ケーキ たんじょうび 誕生日', category: '食べもの', path: faCakeCandles.icon[4] as string },
  { name: 'pizza-slice', keywords: 'ピザ', category: '食べもの', path: faPizzaSlice.icon[4] as string },
  { name: 'drumstick-bite', keywords: 'とりもも 鶏 チキン', category: '食べもの', path: faDrumstickBite.icon[4] as string },
  { name: 'bread-slice', keywords: 'パン しょくぱん 食パン', category: '食べもの', path: faBreadSlice.icon[4] as string },
  { name: 'egg', keywords: 'たまご 卵', category: '食べもの', path: faEgg.icon[4] as string },
  { name: 'cheese', keywords: 'チーズ', category: '食べもの', path: faCheese.icon[4] as string },
  { name: 'hotdog', keywords: 'ホットドッグ', category: '食べもの', path: faHotdog.icon[4] as string },
  { name: 'burger', keywords: 'ハンバーガー', category: '食べもの', path: faBurger.icon[4] as string },
  { name: 'candy-cane', keywords: 'キャンディ つえ 杖 クリスマス', category: '食べもの', path: faCandyCane.icon[4] as string },
  { name: 'mug-hot', keywords: 'マグカップ コーヒー', category: '食べもの', path: faMugHot.icon[4] as string },
  { name: 'bacon', keywords: 'ベーコン', category: '食べもの', path: faBacon.icon[4] as string },
  { name: 'fish-fins', keywords: 'さかな 魚', category: '食べもの', path: faFishFins.icon[4] as string },
  { name: 'plate-wheat', keywords: 'おさら お皿 むぎ 麦', category: '食べもの', path: faPlateWheat.icon[4] as string },
  { name: 'stroopwafel', keywords: 'ワッフル', category: '食べもの', path: faStroopwafel.icon[4] as string },
  { name: 'ghost', keywords: 'おばけ お化け ハロウィン', category: '行事', path: faGhost.icon[4] as string },
  { name: 'gift', keywords: 'プレゼント ギフト', category: '行事', path: faGift.icon[4] as string },
  { name: 'tree', keywords: 'き 木 クリスマスツリー', category: '行事', path: faTree.icon[4] as string },
  { name: 'snowflake', keywords: 'ゆき 雪 けっしょう 結晶', category: '行事', path: faSnowflake.icon[4] as string },
  { name: 'holly-berry', keywords: 'ひいらぎ ヒイラギ クリスマス', category: '行事', path: faHollyBerry.icon[4] as string },
  { name: 'crown', keywords: 'おうかん 王冠', category: '行事', path: faCrown.icon[4] as string },
  { name: 'bell', keywords: 'ベル すず 鈴', category: '行事', path: faBell.icon[4] as string },
  { name: 'sleigh', keywords: 'そり ソリ サンタ', category: '行事', path: faSleigh.icon[4] as string },
  { name: 'menorah', keywords: 'しょくだい 燭台', category: '行事', path: faMenorah.icon[4] as string },
  { name: 'star-and-crescent', keywords: 'つき 月 ほし 星', category: '行事', path: faStarAndCrescent.icon[4] as string },
  { name: 'hat-wizard', keywords: 'ぼうし 帽子 まほう 魔法', category: '行事', path: faHatWizard.icon[4] as string },
  { name: 'skull', keywords: 'どくろ ドクロ ハロウィン', category: '行事', path: faSkull.icon[4] as string },
  { name: 'mask', keywords: 'おめん お面 マスク', category: '行事', path: faMask.icon[4] as string },
  { name: 'wand-magic-sparkles', keywords: 'まほう 魔法 つえ 杖', category: '行事', path: faWandMagicSparkles.icon[4] as string },
  { name: 'sun', keywords: 'たいよう 太陽 ひ 日', category: 'しぜん', path: faSun.icon[4] as string },
  { name: 'cloud', keywords: 'くも 雲', category: 'しぜん', path: faCloud.icon[4] as string },
  { name: 'moon', keywords: 'つき 月', category: 'しぜん', path: faMoon.icon[4] as string },
  { name: 'leaf', keywords: 'はっぱ 葉っぱ', category: 'しぜん', path: faLeaf.icon[4] as string },
  { name: 'seedling', keywords: 'ふたば 双葉 め 芽', category: 'しぜん', path: faSeedling.icon[4] as string },
  { name: 'fire', keywords: 'ひ 火 ほのお 炎', category: 'しぜん', path: faFire.icon[4] as string },
  { name: 'bolt', keywords: 'かみなり 雷 いなずま', category: 'しぜん', path: faBolt.icon[4] as string },
  { name: 'droplet', keywords: 'しずく 雫 みず 水', category: 'しぜん', path: faDroplet.icon[4] as string },
  { name: 'feather', keywords: 'はね 羽根', category: 'しぜん', path: faFeather.icon[4] as string },
  { name: 'clover', keywords: 'クローバー よつば 四つ葉', category: 'しぜん', path: faClover.icon[4] as string },
  { name: 'mountain', keywords: 'やま 山', category: 'しぜん', path: faMountain.icon[4] as string },
  { name: 'rainbow', keywords: 'にじ 虹', category: 'しぜん', path: faRainbow.icon[4] as string },
  { name: 'umbrella', keywords: 'かさ 傘', category: 'しぜん', path: faUmbrella.icon[4] as string },
  { name: 'wind', keywords: 'かぜ 風', category: 'しぜん', path: faWind.icon[4] as string },
  { name: 'car', keywords: 'くるま 車', category: 'のりもの', path: faCar.icon[4] as string },
  { name: 'plane', keywords: 'ひこうき 飛行機', category: 'のりもの', path: faPlane.icon[4] as string },
  { name: 'rocket', keywords: 'ロケット', category: 'のりもの', path: faRocket.icon[4] as string },
  { name: 'ship', keywords: 'ふね 船', category: 'のりもの', path: faShip.icon[4] as string },
  { name: 'train', keywords: 'でんしゃ 電車', category: 'のりもの', path: faTrain.icon[4] as string },
  { name: 'truck', keywords: 'トラック', category: 'のりもの', path: faTruck.icon[4] as string },
  { name: 'bicycle', keywords: 'じてんしゃ 自転車', category: 'のりもの', path: faBicycle.icon[4] as string },
  { name: 'motorcycle', keywords: 'バイク', category: 'のりもの', path: faMotorcycle.icon[4] as string },
  { name: 'tractor', keywords: 'トラクター', category: 'のりもの', path: faTractor.icon[4] as string },
  { name: 'helicopter', keywords: 'ヘリコプター', category: 'のりもの', path: faHelicopter.icon[4] as string },
  { name: 'sailboat', keywords: 'ヨット ふね 船', category: 'のりもの', path: faSailboat.icon[4] as string },
  { name: 'bus', keywords: 'バス', category: 'のりもの', path: faBus.icon[4] as string },
  { name: 'heart', keywords: 'ハート', category: 'かたち', path: faHeart.icon[4] as string },
  { name: 'star', keywords: 'ほし 星 スター', category: 'かたち', path: faStar.icon[4] as string },
  { name: 'music', keywords: 'おんぷ 音符 おんがく 音楽', category: 'かたち', path: faMusic.icon[4] as string },
  { name: 'crown', keywords: 'おうかん 王冠', category: 'かたち', path: faCrown.icon[4] as string },
  { name: 'trophy', keywords: 'トロフィー', category: 'かたち', path: faTrophy.icon[4] as string },
  { name: 'medal', keywords: 'メダル', category: 'かたち', path: faMedal.icon[4] as string },
  { name: 'bookmark', keywords: 'しおり', category: 'かたち', path: faBookmark.icon[4] as string },
  { name: 'anchor', keywords: 'いかり 錨', category: 'かたち', path: faAnchor.icon[4] as string },
  { name: 'key', keywords: 'かぎ 鍵', category: 'かたち', path: faKey.icon[4] as string },
  { name: 'lightbulb', keywords: 'でんきゅう 電球', category: 'かたち', path: faLightbulb.icon[4] as string },
  { name: 'puzzle-piece', keywords: 'パズル', category: 'かたち', path: faPuzzlePiece.icon[4] as string },
  { name: 'gem', keywords: 'ほうせき 宝石 ダイヤ', category: 'かたち', path: faGem.icon[4] as string },
  { name: 'chess-knight', keywords: 'チェス うま 馬', category: 'かたち', path: faChessKnight.icon[4] as string },
  { name: 'football', keywords: 'ラグビー ボール', category: 'かたち', path: faFootball.icon[4] as string },
  { name: 'baseball', keywords: 'やきゅう 野球 ボール', category: 'かたち', path: faBaseball.icon[4] as string },
  { name: 'basketball', keywords: 'バスケ ボール', category: 'かたち', path: faBasketball.icon[4] as string },
  { name: 'futbol', keywords: 'サッカー ボール', category: 'かたち', path: faFutbol.icon[4] as string },
  { name: 'shapes', keywords: 'ずけい 図形', category: 'かたち', path: faShapes.icon[4] as string },
  { name: 'certificate', keywords: 'しょうじょう 賞状 はな 花', category: 'かたち', path: faCertificate.icon[4] as string },
  { name: 'fan', keywords: 'せんぷうき 扇風機', category: 'かたち', path: faFan.icon[4] as string },
  { name: 'hand-peace', keywords: 'ピース て 手', category: 'ひと', path: faHandPeace.icon[4] as string },
  { name: 'hand-spock', keywords: 'て 手', category: 'ひと', path: faHandSpock.icon[4] as string },
  { name: 'thumbs-up', keywords: 'いいね て 手', category: 'ひと', path: faThumbsUp.icon[4] as string },
  { name: 'face-smile', keywords: 'えがお 笑顔 かお 顔', category: 'ひと', path: faFaceSmile.icon[4] as string },
  { name: 'face-grin-hearts', keywords: 'かお 顔 すき 好き', category: 'ひと', path: faFaceGrinHearts.icon[4] as string },
  { name: 'user', keywords: 'ひと 人', category: 'ひと', path: faUser.icon[4] as string },
  { name: 'child', keywords: 'こども 子供', category: 'ひと', path: faChild.icon[4] as string },
  { name: 'person-skating', keywords: 'スケート ひと 人', category: 'ひと', path: faPersonSkating.icon[4] as string },
  { name: 'house', keywords: 'いえ 家', category: 'くらし', path: faHouse.icon[4] as string },
  { name: 'guitar', keywords: 'ギター', category: 'くらし', path: faGuitar.icon[4] as string },
  { name: 'palette', keywords: 'パレット え 絵', category: 'くらし', path: faPalette.icon[4] as string },
  { name: 'camera', keywords: 'カメラ', category: 'くらし', path: faCamera.icon[4] as string },
  { name: 'envelope', keywords: 'てがみ 手紙 メール', category: 'くらし', path: faEnvelope.icon[4] as string },
  { name: 'graduation-cap', keywords: 'そつぎょう 卒業 がくし 学士', category: 'くらし', path: faGraduationCap.icon[4] as string },
  { name: 'shield-halved', keywords: 'たて 盾', category: 'くらし', path: faShieldHalved.icon[4] as string },
  { name: 'robot', keywords: 'ロボット', category: 'くらし', path: faRobot.icon[4] as string },
  { name: 'dice', keywords: 'サイコロ', category: 'くらし', path: faDice.icon[4] as string },
  { name: 'gamepad', keywords: 'ゲーム コントローラー', category: 'くらし', path: faGamepad.icon[4] as string },
  { name: 'bell-concierge', keywords: 'ベル', category: 'くらし', path: faBellConcierge.icon[4] as string },
  { name: 'couch', keywords: 'ソファ', category: 'くらし', path: faCouch.icon[4] as string },
  { name: 'shirt', keywords: 'シャツ ふく 服', category: 'くらし', path: faShirt.icon[4] as string },
  { name: 'tooth', keywords: 'は 歯', category: 'くらし', path: faTooth.icon[4] as string },
  { name: 'glasses', keywords: 'めがね 眼鏡', category: 'くらし', path: faGlasses.icon[4] as string },
  { name: 'headphones', keywords: 'ヘッドホン', category: 'くらし', path: faHeadphones.icon[4] as string },
  { name: 'book', keywords: 'ほん 本', category: 'くらし', path: faBook.icon[4] as string },
]

/** 入力された言葉でアイコンを絞り込む */
export function searchIcons(query: string, category: string | null): CutterIcon[] {
  const q = query.trim().toLowerCase()
  return CUTTER_ICONS.filter((icon) => {
    if (category && icon.category !== category) return false
    if (!q) return true
    return icon.name.includes(q) || icon.keywords.toLowerCase().includes(q)
  })
}
